
[build.environment]
  NPM_VERSION = "7.9.0"
  NODE_VERSION = "15.0.1"

[build]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[context.production]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[context.deploy-preview]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[[redirects]]
  from = "/*"
  to = "/docs/fanatical-support-gcp/:splat"
  status = 301
  force = false